# Header
menu:
  首页: /
  归档: /archives
rss: /atom.xml

# Content
excerpt_link: 阅读全文
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- tag
- tagcloud
- archives
- recent_posts

# Background
background_image: /images/gufeng001.webp
background_title: 图片来自网络

# favicon
favicon: /images/yexiu.webp

#Userinfo
author: 星魂
slogan: 喜好AI人工智能、编程、设计、诗词和游戏的散人
# avatar: /images/code-title.png
avatar_title: 图片来自网络

# Article code panel: cloud doorframe mac
highlightPanel: cloud

#Gitment
gitment:
  owner: 
  repo: 
  client_id: 
  client_secret: 

# Miscellaneous
google_analytics:
gauges_analytics:
google_site_verification: 
baidu_site_verification: 


# 友情链接
blogroll:
  一路眼瞎: https://yiluyanxia.github.io/